domain_name: <%= ENV.fetch('CHOUETTE_DOMAIN_NAME') %>
secret_key_base: <%= ENV.fetch('CHOUETTE_SECRET') %>
devise_secret_key: <%= ENV.fetch('CHOUETTE_SECRET') %>
api_endpoint: 'http://chouette-iev:8080/chouette_iev/'
google_analytic_tracker:
geoportail_api_key:
newrelic_licence_key:
osrm_endpoint: <%= ENV.fetch('CHOUETTE_OSRM') %>
deactivate_formats_referential: neptune,hub,sig,netex # For example: 'hub,sig,neptune'
deactivate_formats_import: neptune,hub,sig,netex # For example: 'hub,sig,neptune'
deactivate_formats_export: neptune,hub,sig,netex # For example: 'hub,sig,neptune'
smtp_delivery_method: sendmail # 'letter_opener' OR 'smtp'
smtp_host: <%= ENV.fetch('CHOUETTE_SMTP_HOST') %>
smtp_port: <%= ENV.fetch('CHOUETTE_SMTP_PORT') %>
smtp_domain: <%= ENV.fetch('CHOUETTE_SMTP_DOMAIN') %>
smtp_user_name: <%= ENV.fetch('CHOUETTE_SMTP_USER') %>
smtp_password: <%= ENV.fetch('CHOUETTE_SMTP_PASSWORD') %>
smtp_authentication:
mailer_sender: <%= ENV.fetch('CHOUETTE_SMTP_SENDER') %>
capistrano_deploy_user:

# IEV config for IEVKit - must be the same as api_endpoint
IEV_VERSION: '1.0'
IEV_HOST: 'http://chouette-iev'
IEV_PORT: '8080'
IEV_PATH: 'chouette_iev'

SPEC_VALIDATION_URL_PROD: 'http://www.chouette.mobi/validation/V2_3'
SPEC_VALIDATION_URL: 'http://preview.chouette.cityway.fr/validation/v24'
PROGRESS_BAR_TIMEOUT: '60000'

openlayers_default_map: osm # For example: 'osm' or 'google_stellite' or 'geoportail_ortho' or 'geoportail_scans' or 'geoportail_cadastre'
restriction_format: # For example: 'hub'

#Redis validation report cache
REDIS_URL: redis://redis:6379/chouette